{% set name = "okapi-em" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/okapi-em-{{ version }}.tar.gz
  sha256: 0fb6063d68cecbe03045f9a195233e7d797560e1d1c020047c7e398bbdd1aa4c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - chafer
    - magicgui
    - napari
    - numpy
    - opencv
    - python >=3.7
    - qtpy
    - scikit-image
    - scipy

test:
  imports:
    - okapi_em
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/okapi-em
  summary: napari plugin to deal with charging artifacts in tomography electron microscopy data
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/rosalindfranklininstitute/okapi-em

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
